sudo: required
services:
  - docker

before_install :
  - docker build -t terriwunde/react-test -f ./client/Dockerfile.dev ./client

scripts:
  - docker run -e CI=true terriwunde/react-test npm test


after_success:

  
  - docker build -t terriwunde/multi-nginx  ./nginx
  - docker build -t terriwunde/multi-server ./server
  - docker build -t terriwunde/multi-worker ./worker
  - docker build -t terriwunde/multi-client ./client

  #Log in to Docker cli
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  #Take images and push to docker hub
  - docker push terriwunde/multi-client
  - docker push terriwunde/multi-nginx    
  - docker push terriwunde/multi-server 
  - docker push terriwunde/multi-worker 

deploy:
  provider: elasticbeanstalk
  region: 'us-east-1'
  app: 'multi-docker'
  env: 'MultiDocker-env'
  bucket_name: 'elasticbeanstalk-us-east-1-144538258201'
  bucket_path: 'docker-multi'
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY

